### Site Settings ###
title: Sam Hedges
description: >-
  I'm an Aspiring Gameplay Programmer and Technical Artist üïπÔ∏è
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: Sam-Hedges/Sam-Hedges.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Sam Hedges
  image: assets/General/pfp.jpg
  # behance           : your_username
  # dribbble          : your_username
  email: sam.hedges.sh@gmail.com
  # facebook          : your_username
  github: Sam-Hedges
  # gitlab            : your_username
  instagram: samhedgesdev
  # kaggle            : your_username
  linkedin: sam-hedges-927476180
  # medium            : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # stackoverflow     : your_user_id
  # tumblr            : your_username.tumblr.com
  twitch: samhedgesdev
  twitter: RetainedStar
  reddit: RetainedStar64
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus:
  shortname: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
